### ISSUE TITLE
Names don't save on content creation

### ISSUE THREAD

**Issue by kevinkace** [tivac/anthracite#100]
When creating a new content item the name won't save when hitting Save, and will instead revert to the default name. It updates and saves correctly afterwards.

**Comment by tivac** [comment]
Looking

**Comment by tivac** [comment]
I can't repro using master.

1. Created new content item
2. Changed name
3. Hit save
4. Noted that name had been saved to Firebase, showed on the item entry, and was updated on the nav.

Did I repro incorrectly?

**Comment by tivac** [comment]
ping @kevinkace to see if this still repos?

**Comment by kevinkace** [comment]
Grabbed latest and looks to work as intended.
