### ISSUE TITLE
"Schedule a publish" doesn't seem to work as intended.

### ISSUE THREAD

**Issue by ctcleary** [tivac/anthracite#125]
It looks like values entered into the "Schedule a publish" popup are not saved to Firebase. The "Save" button itself does not update these values, and they do not appear to update on any input or blur events.

The only way to set either of these fields seems to be the "Publish" and "Unpublish" buttons. Publish will set the "Publish at" to the current time, and "Unpublish" will do the same for the "Until" field, which nulls out the "Publish at" information (including in the Firebase DB). This means you can actually get yourself into a broken state where the "Publish" button will not work because it reads the "Until" timestamp as being in the future, and thus it is an invalid date range.

Expected behavior:
- Hitting "Save" will persist the "Publish"/"Unpublish" timestamps to the DB.
- and/or:
- Persist the new "Publish"/"Unpublish" timestamps to the DB on field blur. (Using reasonable defaults for time of day, such as 12:01 for Publish and 23:59 for unpublish.)

**Comment by ctcleary** [comment]
Note: I'm going to start working on fixing this, but I don't seem to have sufficient permissions to assign myself the issue.

**Comment by tivac** [comment]
The expected behavior should be that changes require hitting the "Save" button. So any manual changes to the fields should require whacking "Save", and then the Publish/Unpublish buttons can just be a convenient shorthand method of modifying those fields.

Seem reasonable?

**Comment by ctcleary** [comment]
Sure thing.

One point on the pub/unpub buttons: I feel like, for historical reasons, we don't want to null out the "Publish" date when we hit "Unpublish." I can easily see a scenario where someone would want to go, "What was the exact date range when we ran that poll?" And nulling the Publish date just seems unnecessary as long as we correctly use the unpublish field on the front end. Not sure if this was intended behavior in the beginning or not.

**Comment by tivac** [comment]
Expected behavior:

- Publish button sets `published_at` to "Right now, minus a few seconds" and clears `unpublished_at` if it's in the past.
- Unpublish button sets `unpublished_at` to "Right now, minus a few seconds" and doesn't touch `published_at`.

**Comment by ctcleary** [comment]
:+1:
