### ISSUE TITLE
Add Markdown type w/ in-crucible previewing

### ISSUE THREAD

**Issue by kevinkace** [tivac/anthracite#59]
We've been using [Remarkable](https://www.npmjs.com/package/remarkable) in GW.com, but perhaps there's something better.

**Comment by tivac** [comment]
I'm a bit hesitant to add this, since I don't think a CMS will ever be a good place to do serious editing.

Will need to ponder on it a bit.

**Comment by kevinkace** [comment]
D'oh, ya, I was more so thinking about JsSrv land (now added https://github.com/arenanet/web-team/issues/27).

Though might be nice to have a preview tab in the CMS, similar to GH comments.

**Comment by tivac** [comment]
I suppose seeing a generic preview to verify formatting would be useful, yeah.

Should probably add a new `markdown` type that encapsulates all of this to simplify things.

**Comment by tivac** [comment]
https://github.com/bevacqua/woofmark seems promising-ish, though I've been bitten by his stuff not quite being as nice as it looks at first glance before. Looking around a bit more to see what other options are available.

**Comment by tivac** [comment]
May actually just use `codemirror` & `remarkable` (or some other markdown parser) directly, now that I think about it some more. Already have `codemirror` included so also loading markdown mode should be pretty straightforward & not bloat the bundle too much further.

**Comment by tivac** [comment]
@Ryan-McMillan all yours :smile:
